const CONTENT_DEFAULTS={};
function parseContent(text){const data={};text.split(/\r?\n/).forEach(line=>{if(/^\s*#/.test(line))return;const m=line.match(/^\s*([A-Za-z0-9_]+)\s*:\s*(.*?)\s*$/);if(m&&m[2])data[m[1].toLowerCase()]=m[2]});return data}
function applyContent(data){document.querySelectorAll('[data-key]').forEach(el=>{const value=data[el.dataset.key];if(value)el.textContent=value});document.querySelectorAll('[data-image-key]').forEach(img=>{const value=data[img.dataset.imageKey];if(!value)return;img.onload=()=>{img.hidden=false;const ph=document.querySelector('[data-placeholder="'+img.dataset.imageKey+'"]');if(ph)ph.hidden=true};img.src=value});if(data.calendar_url)document.querySelectorAll('[data-calendar-link]').forEach(link=>link.href=data.calendar_url)}
fetch('content.txt?v='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.text():Promise.reject()).then(t=>applyContent(parseContent(t))).catch(()=>{});
function formatEventTime(event){if(event.all_day)return'All day';const start=new Date(event.start),end=new Date(event.end);const day=start.toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'});const from=start.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});const to=end.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});return day+' · '+from+'–'+to}
function renderCalendarEvents(events){const wrap=document.getElementById('calendarEvents');if(!wrap||!events.length)return;wrap.textContent='';events.slice(0,8).forEach(event=>{const start=new Date(event.start),item=document.createElement('article'),date=document.createElement('div'),copy=document.createElement('div'),title=document.createElement('h3'),when=document.createElement('div'),where=document.createElement('div'),month=document.createElement('small');item.className='event-item';date.className='event-date';month.textContent=start.toLocaleDateString([],{month:'short'});date.append(month,document.createTextNode(start.getDate()));copy.className='event-copy';title.textContent=event.title||'Project Rebound event';when.className='event-when';when.textContent=formatEventTime(event);copy.append(title,when);if(event.location){where.className='event-where';where.textContent=event.location;copy.append(where)}item.append(date,copy);wrap.append(item)})}
fetch('calendar-events.json?v='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(data=>renderCalendarEvents(Array.isArray(data.events)?data.events:[])).catch(()=>{});
const PR=(()=>{const slides=[...document.querySelectorAll('.slide')],wrap=document.getElementById('dots');let index=0,timer;wrap.innerHTML=slides.map((_,i)=>'<button aria-label="Go to screen '+(i+1)+'"></button>').join('');const dots=[...wrap.children];function paint(){slides.forEach((s,i)=>s.classList.toggle('on',i===index));dots.forEach((d,i)=>d.classList.toggle('on',i===index))}function run(){clearInterval(timer);timer=setInterval(()=>go(index+1),14000)}function go(n){index=(n+slides.length)%slides.length;paint();run()}dots.forEach((d,i)=>d.addEventListener('click',()=>go(i)));document.querySelector('.prev').addEventListener('click',()=>go(index-1));document.querySelector('.next').addEventListener('click',()=>go(index+1));document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')go(index+1);if(e.key==='ArrowLeft')go(index-1)});paint();run();return{go}})();
(function clock(){function tick(){const n=new Date();document.getElementById('clockTime').textContent=n.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});document.getElementById('clockDate').textContent=n.toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'})}tick();setInterval(tick,15000)})();
setTimeout(()=>location.replace(location.pathname+'?refresh='+Date.now()),15*60*1000);
